# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  commands:
    - pip install poetry
    # VIRTUAL_ENV needs to be set manually for now.
    # See https://github.com/readthedocs/readthedocs.org/pull/11152/
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
    - pdoc -o $READTHEDOCS_OUTPUT/html -t templates -e spkb=https://github.com/whitelynx/spkb/blob/main/spkb/ spkb
